default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: clone_development

test:
  <<: *default
  database: clone_test

production:
  <<: *default
  database: clone_production
  username: clone
  password: <%= ENV['CLONE_DATABASE_PASSWORD'] %>